# Supabase Configuration
project_id = "your-project-id"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
external_url = "http://localhost:3000"

[edge_functions]
enabled = true
port = 54323

[functions.auto-push]
verify_jwt = false

[secrets]
# These will be set via: supabase secrets set KEY=value
# VAPID_PRIVATE_KEY = "u2wSemK8AM2p6L_o0H51jPmBgsgPX1--1cOOoSU5nAo"
# VAPID_SUBJECT = "mailto:admin@bd-evidencija.com"
